@echo off
:: 01 intro
ytd https://www.youtube.com/watch?v=kt6V4ai60fI
:: 02
ytd https://www.youtube.com/watch?v=tmeCWULSTHc
:: 03
ytd https://www.youtube.com/watch?v=nQfHZ2DEJ8c
:: 04
ytd https://www.youtube.com/watch?v=L-ReMHiavPM
:: 05
ytd https://www.youtube.com/watch?v=N29ZJ-o31xs
:: 06
ytd https://www.youtube.com/watch?v=Bkt8B3kLATQ
:: 07
ytd https://www.youtube.com/watch?v=G8-z91acgG4
:: 08
ytd https://www.youtube.com/watch?v=7rbV8aWkcqY
:: 09
ytd https://www.youtube.com/watch?v=iZLXnNiZm_s
:: 10
ytd https://www.youtube.com/watch?v=S9ORTYmXwdE
:: 11
ytd https://www.youtube.com/watch?v=Sqw2bww93Zo
:: 12
ytd https://www.youtube.com/watch?v=8GkQfdAXZP0
:: 13
ytd https://www.youtube.com/watch?v=tpPtItWqmlg
:: 14
ytd https://www.youtube.com/watch?v=NUdu1n-ML98
:: 15
ytd https://www.youtube.com/watch?v=tGxuitjtO88
:: 16
ytd https://www.youtube.com/watch?v=EpGQnhjXBq8
:: 17
ytd https://www.youtube.com/watch?v=5WIqHJDQ_p4
:: 18
ytd https://www.youtube.com/watch?v=eai0nHhAC8w
:: 19
ytd https://www.youtube.com/watch?v=IEa1N0rTtbc
:: 20
ytd https://www.youtube.com/watch?v=Q6GFu8-Z4rY
:: 21
ytd https://www.youtube.com/watch?v=kmVXVJE08eQ
:: 22
ytd https://www.youtube.com/watch?v=QKc_i90chVg
:: 23
ytd https://www.youtube.com/watch?v=TV9TfwHXuqs
:: 24
ytd https://www.youtube.com/watch?v=nv0ey5UyOmY
:: 25
ytd https://www.youtube.com/watch?v=CnTXwAuDi9Y
:: 26
ytd https://www.youtube.com/watch?v=k26euOG6zAk
:: 27
ytd https://www.youtube.com/watch?v=gLK4Qm6jte8
:: 28
ytd https://www.youtube.com/watch?v=j0Z2EbuJXGU
:: 29
ytd https://www.youtube.com/watch?v=QkokVv0owSE
:: 30
ytd https://www.youtube.com/watch?v=CL94EnGqB4Q
:: 31
ytd https://www.youtube.com/watch?v=OYNpIeu9czw
:: 32
ytd https://www.youtube.com/watch?v=hzoMJQlEv5M
:: 33
ytd https://www.youtube.com/watch?v=8z6My18WZqA
:: 34
ytd https://www.youtube.com/watch?v=t8flQP5jy-Q
:: 35
ytd https://www.youtube.com/watch?v=MdYrslpUezU
:: 36
ytd https://www.youtube.com/watch?v=pWnMpdN_g98
:: 37
ytd https://www.youtube.com/watch?v=HuZurY0ghDI
:: 38
ytd https://www.youtube.com/watch?v=36184dDAqtM
:: 39
ytd https://www.youtube.com/watch?v=yFpHbBnsK_c
:: 40
ytd https://www.youtube.com/watch?v=koN1ge8bewI
:: 41 and final
ytd https://www.youtube.com/watch?v=2XhDi5GoNUI